### ISSUE TITLE
Tekstvoorstel

### ISSUE THREAD

**Issue by roelandordelman** [CLARIAH/wp5-mediasuite#1]
"Kies een van de voorgedefineerde recepten" -> "Kies een recept"

**Comment by jblom** [comment]
Dank voor uw bericht. Het is opgelost.

**Comment by roelandordelman** [comment]
http://mediasuite.clariah.beeldengeluid.nl/recipe/avresearcherxl
it says: loading collection list....
but nothing happens. I'm on a UT connection.
