### ISSUE TITLE
Result list does not update automatically when switching to other collections 

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5-mediasuite#41]
If I switch tab from one collection to another one, I have to resubmit the query each time, otherwise the result list doesn't update.

**Comment by jblom** [comment]
This has been solved: results from different collections are all shown in different collapsable boxes. Check it out to see. I'll optimise the UI later on

**Comment by lilimelgar** [comment]
Great! the result lists in boxes per collection are much more understandable/flexible. However, if you switch the collection tab above, the result list boxes persist (do not update automatically) even if I close (x) one collection tab, its result list box remains.

**Comment by lilimelgar** [comment]
Fixed! :thumbsup:
