### ISSUE TITLE
When clicking on "Last" page icon, pagination icons get messed up if there are no results

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5-mediasuite#43]

**Comment by jblom** [comment]
this is solved now, however the big underlying problem is that the calculation of the number of pages is off in many cases. This is because of the tricky layered search engine and needs to be addressed thoroughly.

**Comment by lilimelgar** [comment]
Jaap said before: "now whenever the last page is actually not yielding any results, the paging icons are not shown.

The big problem that apparently the amount of result pages isn't always accurate. In quite a lot of cases the last page actually does not exist.

This needs to be investigated properly at some point"

**Comment by lilimelgar** [comment]
Yes 👍 I changed label to issues to include this in the Knowledge base.
